[package]
name = "{{ project-name }}-ebpf"
version = "0.1.0"
edition = "2018"

[dependencies]
aya-bpf = { git = "http://github.com/alessandrod/aya", branch = "main" }
{{ project-name }}-common = { path = "../{{ project-name }}-common" }
memoffset = "0.6"

[[bin]]
name = "{{ project-name }}"
path = "src/main.rs"

[profile.dev]
panic = "abort"
overflow-checks = false

[profile.release]
panic = "abort"

[workspace]
members = []