[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
aya = { git = "https://github.com/alessandrod/aya", branch="main" }
{{project-name}}-common = { path = "../{{project-name}}-common", features=["userspace"] }
anyhow = "1.0.42"
ctrlc = "3.1"

[[bin]]
name = "{{project-name}}"
path = "src/main.rs"
